CREATE DATABASE IF NOT EXISTS GameDB CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE GameDB;

CREATE TABLE IF NOT EXISTS Account (
    AccountId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    AccountName VARCHAR(50) NOT NULL,
    PasswordHash VARCHAR(160) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (AccountId),
    UNIQUE KEY UQ_Account_AccountName (AccountName)
) ENGINE=InnoDB;
